[package]
name = "rustic-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
reqwest = "0.11.23"
tokio = { version = "1.35.1", features = ["full"] }
tui = "0.19.0"
