version: "3.8"

services:
  server:
    build:
      dockerfile: server/Dockerfile
    volumes:
      - .:/app
      - ../shared_lib:/app/shared_lib
      - cargo-cache:/usr/local/cargo/registry
      - data:/rustic
    command: sh -c "cargo run --bin rustic-server"
    ports:
      - "127.0.0.1:8001:3000"
    environment:
      RUST_LOG: "debug,sqlx=warn"
      SQLITE_FILE: "/rustic/time_tracker.db"
      SERVER_ADDR: "0.0.0.0:3000"

  monitor_workday:
    build:
      dockerfile: monitor_workday/Dockerfile
    volumes:
      - .:/app
      - ../shared_lib:/app/shared_lib
      - cargo-cache:/usr/local/cargo/registry
    command: sh -c "cargo run --bin monitor_workday"
    depends_on:
      - server
    environment:
      RUST_LOG: "info,debug,sqlx=warn"
      SERVER_URL: "http://server:3000"

volumes:
  cargo-cache:
  data:

