#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )


myArray=("rustic-monitor_workday-1" "rustic-server-1" "rustic_db")
tempArray=()
function start() {
    cd "$SCRIPT_DIR"
    docker compose up --build -d
}

function stop() {
    cd "$SCRIPT_DIR"
    docker compose down
}

function ui() {
    cd "$SCRIPT_DIR"
    docker ps --format '{{.Names}}' >test.txt
    output=$(<test.txt)
    for i in $output; do
        if [[ ${myArray[@]} =~ $i ]]; then
            tempArray+=($i)
        fi

    done
    if [[ ${tempArray[@]}  == ${myArray[@]} ]]; then
        cd "$SCRIPT_DIR"
        COMMAND= cd "${SCRIPT_DIR}/tui" && cargo run
        x-terminal-emulator -e "{$COMMAND}"
        cd "$SCRIPT_DIR"
    else
        start
        ui
    fi
}

for l in $@; do
    case $l in
    start) start ;;
    stop) stop ;;
    ui) ui ;;
    esac
done
