version: "3.8"

services:
  rustic-server:
    build:
      context: ../  # Set the context to the parent directory
      dockerfile: server/Dockerfile
      target: final
    volumes:
      - .:/app
      - ../shared_lib:/app/shared_lib
      - cargo-cache:/usr/local/cargo/registry
    command: sh -c "cargo run --bin rustic-server"
    ports:
      - "127.0.0.1:8000:3000"
    depends_on:
      - db
    environment:
      RUST_LOG: "debug,sqlx=warn"
      DATABASE_URL: "postgres://rustic_user:password@db:5432/rustic_db"
      SERVER_ADDR: "0.0.0.0:3000"

  db:
    build: ../db/db_init/
    container_name: rustic_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: rustic_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustic_db

volumes:
  cargo-cache:
  postgres-data:
