version: "3.8"

services:
  rustic-server:
    build: .
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    command: sh -c "cargo run --bin rustic-server"
    ports:
      - "127.0.0.1:8000:3000"
    depends_on:
      - db
    environment:
      RUST_LOG: "debug,sqlx=warn"

  db:
    build: ../db/db_init/
    container_name: rustic_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: rustic_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustic_db

volumes:
  cargo-cache:
  postgres-data:
