version: "3.9" # Use the desired version of Docker Compose

services:
  postgres:
    build: ./db_init/
    container_name: rustic_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: rustic_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustic_db
